import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import MenuBar from "@/components/MenuBar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ConvertPlus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="scroll-smooth">
      <body className={nunito.className}>
        <div className="bg-white-100 p-2">
          <MenuBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
